<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYcCGP40\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYcCGP40/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYcCGP40.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYcCGP40\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYcCGP40\App_KernelDevDebugContainer([
    'container.build_hash' => 'YcCGP40',
    'container.build_id' => 'f1d416f6',
    'container.build_time' => 1711648133,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYcCGP40');
